site_name: AWSIM Labs Documentation

site_url: https://autowarefoundation.github.io/AWSIM-Labs
repo_url: https://github.com/autowarefoundation/AWSIM-Labs
edit_uri: https://github.com/autowarefoundation/AWSIM-Labs/tree/main/docs

theme:
  name: material
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.path
    - content.tabs.link
  icon:
    logo: fontawesome/solid/car
    repo: fontawesome/brands/github
  language: en
  palette:
    - scheme: default
      primary: light-green
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  font:
    text: Roboto
    code: Roboto Mono
  version:
    provider: mike

extra_css:
  - assets/css/extra.css
  - https://use.fontawesome.com/releases/v5.15.4/css/all.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - awesome-pages
  - exclude:
      regex:
        - ^(?!(.*/)?assets/).*\.(?!(.*\.)?md|(.*\.)?svg|(.*\.)?png|(.*\.)?gif|(.*\.)?jpg).*$
        - ^(.*/)?[^.]*$
  - macros
  - mkdocs-video
  - same-dir
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - fontawesome_markdown
  - footnotes
  - md_in_html
  - mdx_math
  - mdx_truly_sane_lists:
      nested_indent: 4
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
      format: svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 3
  - tables

nav:
  - Home: index.md

  - Getting started:
    - Quick Start Demo: GettingStarted/QuickStartDemo/index.md
    - Setup Unity Project: GettingStarted/SetupUnityProject/index.md
    - Using OpenSCENARIO: GettingStarted/UsingOpenSCENARIO/index.md
    - Parking Area: GettingStarted/ParkingArea/index.md



  - Introduction:
    - Autoware: Introduction/Autoware/index.md
    - AWSIM Labs: Introduction/AWSIM/index.md
    - CombinationWithAutoware: Introduction/CombinationWithAutoware/index.md

  - Project guide:
    - Directory: ProjectGuide/Directory/index.md
    - Hotkey List: ProjectGuide/HotkeyList/index.md
    - Scenes: ProjectGuide/Scenes/index.md
    - Git Branch: ProjectGuide/GitBranch/index.md
    - External Libraries: ProjectGuide/ExternalLibraries/index.md

  - Components:
    - Clock:
      - Clock Publisher: Components/Clock/ClockPublisher/index.md
    - Vehicle:
      - Ego Vehicle: Components/Vehicle/EgoVehicle/index.md
      - URDF And Sensors: Components/Vehicle/URDFAndSensors/index.md
      - Dynamic Sensor Placement: Components/Vehicle/DynamicSensorPlacement/index.md
      - Add New Vehicle:
        - Add Vehicle: Components/Vehicle/AddNewVehicle/AddAVehicle/index.md
        - Add Colliders: Components/Vehicle/AddNewVehicle/AddColliders/index.md
        - Add Sensors: Components/Vehicle/AddNewVehicle/AddSensors/index.md
        - Add Visual Elements: Components/Vehicle/AddNewVehicle/AddVisualElements/index.md
      - Customize Slip: Components/Vehicle/CustomizeSlip/index.md
      - FollowCamera: Components/Vehicle/FollowCamera/index.md
      - VPP Integration: Components/Vehicle/VPPIntegration/index.md
    - Sensors:
      - LiDAR Sensor:
        - LiDAR Sensor: Components/Sensors/LiDARSensor/LiDARSensor/index.md
        - Add New LiDAR: Components/Sensors/LiDARSensor/AddNewLiDAR/index.md
        - Read Material Information: Components/Sensors/LiDARSensor/ReadMaterialInformation/index.md
        - RGLUnityPlugin: Components/Sensors/LiDARSensor/RGLUnityPlugin/index.md
      - Camera Sensor: Components/Sensors/CameraSensor/index.md
      - IMU Sensor: Components/Sensors/IMUSensor/index.md
      - GNSS Sensor: Components/Sensors/GNSSSensor/index.md
      - Vehicle Status Sensor: Components/Sensors/VehicleStatusSensor/index.md
    - Environment:
      - AWSIM Environment: Components/Environment/AWSIMEnvironment/index.md
      - Add New Environment:
        - Add Environment: Components/Environment/AddNewEnvironment/AddEnvironment/index.md
        - Add RandomTraffic:
          - Load Items From Lanelet: Components/Environment/AddNewEnvironment/AddRandomTraffic/LoadItemsFromLanelet/index.md
          - Add Random Traffic: Components/Environment/AddNewEnvironment/AddRandomTraffic/AddRandomTraffic/index.md
          - Add Traffic Intersection: Components/Environment/AddNewEnvironment/AddRandomTraffic/AddTrafficIntersection/index.md
        - Add TrafficLights: Components/Environment/AddNewEnvironment/AddTrafficLights/index.md
      - Create PCD: Components/Environment/CreatePCD/index.md
      - LaneletBoundsVisualizer: Components/Environment/LaneletBoundsVisualizer/index.md
      - SmokeSimulator: Components/Environment/SmokeSimulator/index.md
      - V2I: Components/Environment/V2I/index.md
    - Traffic:
      - Traffic Components: Components/Traffic/TrafficComponents/index.md
      - Random Traffic:
        - Random Traffic Simulator: Components/Traffic/RandomTraffic/RandomTrafficSimulator/index.md
        - Yielding Rules: Components/Traffic/RandomTraffic/YieldingRules/index.md
        - Add Random Traffic Environment: Components/Traffic/RandomTraffic/AddRandomTrafficEnvironment/index.md
      - NPCs:
        - Spawn NPCs from RVIZ: Components/Traffic/NPCs/RvizNPCSpawner/index.md
        - Pedestrian: Components/Traffic/NPCs/Pedestrian/index.md
        - Vehicle: Components/Traffic/NPCs/Vehicle/index.md
    - ROS2:
      - ROS2 topic list: Components/ROS2/ROS2TopicList/index.md
      - Add custom ROS2 msg: Components/ROS2/AddACustomROS2Message/index.md
      - ROS2 For Unity: Components/ROS2/ROS2ForUnity/index.md
    - OpenSCENARIO:
      - Setup Unity project for scenario simulation: Components/ScenarioSimulation/SetupUnityProjectForScenarioSimulation/index.md
      - Preparing the connection between AWSIM and scenario_simulator_v2: Components/ScenarioSimulation/PreparingTheConnectionBetweenAWSIMAndScenarioSimulator/index.md

  - Developer guide:
    - How to Contribute: DeveloperGuide/HowToContribute/index.md
    - VSCode Configuration: DeveloperGuide/EditorSetup/VSCode/index.md
    - Rider Configuration: DeveloperGuide/EditorSetup/JetBrainsRider/index.md
    - Graphy Asset Setup: DeveloperGuide/EditorSetup/Graphy/index.md
    - Vehicle Physics Pro CE Setup: DeveloperGuide/EditorSetup/VPPCommunityEdition/index.md
    - Trouble shooting: DeveloperGuide/TroubleShooting/index.md
    - Documentation: DeveloperGuide/Documentation/index.md
    - License : DeveloperGuide/License/index.md
    - Contact : DeveloperGuide/Contact/index.md
